name: outletnerd
description: "A melhor loja nerd/geek do Brasil!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner.png
    - assets/Mario.jpg
    - assets/zoro.jpg
    - assets/Pikachu.jpg
    - assets/payments.png
    - assets/techne.png

