name: outletnerd
description: "A melhor loja nerd/geek do Brasil!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner.png
    - assets/Mario.jpg
    - assets/zoro.jpg
    - assets/Pikachu.jpg
    - assets/payments.png
    - assets/techne.png
    - assets/produtos.json
    - assets/beybladeDragoon.jpg
    - assets/legoXwing.jpg
    - assets/hwMario.jpg
    - assets/charmander.jpg
    - assets/deku.jpg
    - assets/batmovel.jpg
    - assets/funkoGoku.jpg
    - assets/slimeGalaxy.jpg
    - assets/yoyoMetal.jpg
    - assets/quadroZelda.jpg
    - assets/luminariaPoke.jpg
    - assets/almofadaNaruto.jpg
    - assets/relogioSW.jpg
    - assets/posterLuffy.jpg
    - assets/sonicDecor.jpg
    - assets/letreiroAnime.jpg
    - assets/portaLivrosBatman.jpg
    - assets/camisaAkatsuki.jpg
    - assets/camisaOnePiece.jpg
    - assets/moletomValor.jpg
    - assets/camisaVegeta.jpg
    - assets/camisaMario.jpg
    - assets/blusaHP.jpg
    - assets/boneStarWars.jpg
    - assets/camisaAOT.jpg
    - assets/moletomSonic.jpg
    - assets/op1.jpg
    - assets/naruto5.jpg
    - assets/monica190.jpg
    - assets/tg3.jpg
    - assets/jjk1.jpg
    - assets/spiderSpec.jpg
    - assets/aot2.jpg
    - assets/csm1.jpg
    - assets/xmen27.jpg
    - assets/demonslayerv1.jpg
    - assets/camiseta_naruto.jpg
    - assets/quadroneon.jpg
    - assets/terrarioMinecraft.jpg

